### PR TITLE
updates mono to 5.4

### PR DESCRIPTION
**Pull request by tamizhvendan**

### CODE REVIEW

**Comment by tamizhvendan** [comment]
Hi @ademar, Can you accept this pull request and release a new mono-binary?

**Comment by ademar** [comment]
@tamizhvendan I'll release the binary later today. thanks.

**Comment by tamizhvendan** [comment]
Thanks @ademar. Just out of curiosity. I tried to do it by myself but I am facing this error 

```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 ca-certificates-mono : Depends: mono-runtime (>= 3.0~) but it is not going to be installed
                        Depends: libmono-corlib4.5-cil (>= 4.0.0~alpha1) but it is not going to be installed
                        Depends: libmono-security4.0-cil (>= 3.0.6) but it is not going to be installed
                        PreDepends: mono-runtime-common but it is not going to be installed
 mono-complete : Depends: mono-runtime (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-runtime-sgen (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-utils (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-mcs (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-roslyn (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-csharp-shell (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-4.0-gac (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: mono-4.0-service (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: monodoc-base (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: monodoc-manual (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
                 Depends: libmono-cil-dev (= 5.4.0.201-0xamarin10+debian9b1) but it is not going to be installed
 mono-devel : Depends: mono-runtime (>= 3.0~) but it is not going to be installed
              Depends: libc6 (>= 2.24) but 2.19-0ubuntu6.13 is to be installed or
                       libc6.1 (>= 2.24) but it is not installable or
                       libc0.1 (>= 2.24) but it is not installable
```

I am not sure how to fix this one

**Comment by ademar** [comment]
I am also struggling to get it working :(

**Pull request merged**
